apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-d0i1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-d0i1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-d0i1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-d0i1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-d0i1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xygk-tenant/rhtap-demo-app/hacbs-test-project-d0i1@sha256:5b4ef28f0f6eb9bc1560da4c7e759bb3563bb335e549f95d02df55495ff663b7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
